name: "Assemble Offline TrustRoot"
description: "A GitHub Action to download a TrustRoot for use in airgapped environments"
author: "falcorocks"
inputs:
  example-input:
    description: "An example input for the action."
    required: false
    default: "default-value"
outputs:
  example-output:
    description: "An example output from the action."
runs:
  using: "docker"
  image: "Dockerfile"
branding:
  icon: "package"
  color: "blue"
